/*
 * The full project archive. Every entry backs a real, built project inside
 * the learning/ portfolio repo. Tracks match the six job tracks: ai, data,
 * quant, hardware, health, product. Keep titles clean, no folder numbers,
 * since those are internal build bookkeeping, not public-facing.
 */

const GH = "https://github.com/K-Divyasri/";

const PROJECTS = [
  // ---- AI Engineer -----------------------------------------------------
  { title: "Data Detective", track: "ai", desc: "Unknown CSVs hide type errors and gaps, so built a Python and pandas CLI that coerces text numbers, reports missing data, and charts columns, surfacing 26.7% missing budgets across 45 rows in one command", tags: ["Python", "Pandas", "CLI"], metric: "Flagged 26.7% missing budgets in 45 rows", repo: GH + "data-detective" },
  { title: "Prompt Engineering Lab", track: "ai", desc: "Prompt choice was guesswork, so built a benchmark scoring five prompt styles on 30 labelled support tickets with accuracy, parse rate and confusion matrices, plus pydantic validated JSON output, covered by 27 tests", tags: ["Prompting", "Evaluation"], metric: "5 prompt styles scored on 30 labelled tickets", repo: GH + "prompt-engineering-lab" },
  { title: "Document Summarizer", track: "ai", desc: "Long documents overflow a model context window, so built a MapReduce summarizer chunking on sentence boundaries with overlap and recursive reduction, condensing a 1686 token article into a 91 token summary in 3 rounds", tags: ["LLM", "Chunking"], metric: "1686 tokens condensed to 91 in 3 rounds", repo: GH + "document-summarizer" },
  { title: "Structured Data Extractor", track: "ai", desc: "Resumes arrive as free text, so built a pydantic v2 schema gate, SQLite store and FastAPI endpoint that reject malformed records, extracting 42 of 48 fields from six sample resumes offline", tags: ["Pydantic", "FastAPI"], metric: "42 of 48 fields extracted offline, 27 tests", repo: GH + "structured-data-extractor" },
  { title: "Embeddings Explorer", track: "ai", desc: "Keyword search misses paraphrases, so built semantic search, k means clustering and 2D maps over 500 MiniLM sentence embeddings, where a small furry pet query returns rabbits and hamsters", tags: ["Embeddings", "Clustering"], metric: "0.806 cluster purity across 13 topics", repo: GH + "embeddings-explorer" },
  { title: "Chat With Your PDF", track: "ai", desc: "Language models invent answers about private documents, so built a RAG pipeline from scratch with chunking, hashing vectors and retrieval, answering with page citations and refusing out of scope questions, verified by 25 tests", tags: ["RAG", "PDF"], metric: "Page cited answers, off topic question refused", repo: GH + "chat-with-your-pdf" },
  { title: "Production RAG Platform", track: "ai", desc: "Keyword search collapses on reworded questions, so engineered hybrid BM25 and vector retrieval in Qdrant with RRF fusion and cross encoder reranking on FastAPI, holding recall@5 at 1.000 where keyword alone scored 0.667", tags: ["Qdrant", "Hybrid Search", "FastAPI"], metric: "Paraphrase recall@5 0.667 to 1.000", featured: true, repo: GH + "rag-real-knowledge-base" },
  { title: "RAG Evaluation Harness", track: "ai", desc: "Quality regressions ship unnoticed, so built an evaluation harness scoring context precision, faithfulness, answer relevance and correctness with LLM as judge, gating CI so a broken config scored 0.690 RAGAS and exited 1", tags: ["Evaluation", "CI"], metric: "Good config 0.949 vs broken 0.690, gate exits 1", repo: GH + "rag-evaluation-harness" },
  { title: "Function Calling Assistant", track: "ai", desc: "Models cannot do arithmetic or read databases reliably, so implemented a reason act observe tool loop over four tools with an AST calculator, parameterized SQL and a step limit, verified by 24 tests", tags: ["Agents", "Tool Use"], metric: "Two tools called in one turn, 24 tests", repo: GH + "function-calling-assistant" },
  { title: "ReAct Research Agent", track: "ai", desc: "Chatbots answer research questions without receipts, so built a ReAct agent from scratch that searches, reads and cites every claim, then critiques its own draft, returning three cited sources on a coral bleaching question", tags: ["Agents", "Grounding"], metric: "3 cited sources, self critique passed, 29 tests", repo: GH + "react-research-agent" },
  { title: "Multi Agent Content Team", track: "ai", desc: "One prompt cannot research, write and edit well, so architected Researcher, Writer and Editor agents on a hand built state machine with a revision loop and human sign off, approving after one revision", tags: ["Multi Agent", "Orchestration"], metric: "Approved after 1 revision, 18 tests", repo: GH + "multi-agent-content-team" },
  { title: "SQL Agent", track: "ai", desc: "Generated SQL can delete or leak data, so engineered a text to SQL agent with three safety layers, a SELECT check, read only connection and write denying authorizer, refusing DELETE while answering revenue queries", tags: ["Agents", "SQL"], metric: "3 safety layers, DELETE refused, 39 tests", repo: GH + "sql-agent" },
  { title: "Guardrails Safety Layer", track: "ai", desc: "Raw chatbots follow injected instructions and echo card numbers, so built guardrails for prompt injection, PII redaction, topic scope and schema checks, handling 19 of 19 red team cases for a bank chatbot", tags: ["Safety", "Red Team"], metric: "19/19 red team cases handled", repo: GH + "guardrails-safety-layer" },
  { title: "CI/CD Cloud Deployment", track: "ai", desc: "Manual releases break silently, so automated GitHub Actions lint, pytest and Docker build on every push for a FastAPI service with a non root image, health checks and git SHA tags, passing 15 tests", tags: ["CI/CD", "Docker"], metric: "15 tests, Docker image reports healthy", repo: GH + "cicd-cloud-deployment" },
  { title: "Fine Tuning: LoRA vs Prompting", track: "ai", desc: "Fine tuning versus RAG versus prompting needs numbers, so trained head only, full and LoRA classifiers in NumPy, where LoRA hit 0.967 against 0.983 for full tuning with 12.9x fewer parameters", tags: ["LoRA", "PEFT"], metric: "LoRA 0.967 vs full 0.983, 12.9x fewer parameters", repo: GH + "fine-tuning-lora" },
  { title: "VisionQA (Multimodal App)", track: "ai", desc: "Pixel statistics misjudge images, so built an offline vision question answering app with brightness, edge and color features plus a table grid detector, showing a pale blue sky misread as white", tags: ["Multimodal", "Vision"], metric: "6 sample images, 35 tests", repo: GH + "multimodal-app" },
  { title: "Semantic Search Recommender", track: "ai", desc: "Keyword search misses meaning and ranking order matters, so built TF IDF semantic search and more like this, then A/B tested rankers on 6 queries, lifting NDCG@10 from 0.920 to 0.974 with blended ranking", tags: ["Recommenders", "A/B Testing"], metric: "NDCG@10 0.920 to 0.974 on 6 queries", repo: GH + "semantic-search-recommender" },
  { title: "MCP Server and Client", track: "ai", desc: "Tool integrations were bespoke, so implemented a Model Context Protocol server with 4 tools, 1 resource and 1 prompt over stdio and HTTP, tested over real JSON RPC with 40 tests", tags: ["MCP", "Protocol"], metric: "40 tests over real JSON RPC", repo: GH + "mcp-server-client" },
  { title: "LLM Cost Optimizer", track: "ai", desc: "Simple traffic hits the priciest model, so engineered a gateway that routes by difficulty with exact and semantic caching, cutting cost 56% ($0.0125 to $0.0055) on 20 requests while matching frontier accuracy", tags: ["Routing", "Semantic Cache"], metric: "56% cost cut, full accuracy kept", repo: GH + "llm-cost-optimizer" },
  { title: "Browser Use Safety Agent", track: "ai", desc: "Browser agents can delete accounts or place orders unchecked, so engineered a Playwright agent behind an action allowlist, destructive denylist, domain allowlist and audit log, passing 13 of 13 red team cases", tags: ["Playwright", "Agent Safety"], metric: "13/13 red team cases handled", repo: GH + "browser-use-safety-agent" },
  { title: "LLM Red Team Jailbreak Benchmark", track: "ai", desc: "Regex guardrails have blind spots, so built an OWASP LLM Top 10 attack harness with 29 payloads, finding 16 bypasses in the default guard and hardening it to 0 vulnerabilities at 90% pass rate", tags: ["Red Team", "OWASP LLM Top 10"], metric: "45% to 90% pass rate, 3 false positives", repo: GH + "llm-redteam-jailbreak-benchmark" },
  { title: "On Device SLM Benchmark", track: "ai", desc: "Local or API inference needs measurements, so built a harness scoring a quantized GGUF model against Claude Haiku on accuracy, latency and cost per 1000 calls over 12 questions, with offline engines", tags: ["Quantization", "Edge AI"], metric: "Offline demo: local 100% easy, 0% hard", repo: GH + "on-device-slm-benchmark" },
  { title: "Repo Aware Codebase Agent", track: "ai", desc: "Prose style chunking splits code apart, so built an AST symbol index with call graph expansion and a sandboxed agent that applied and verified fixes for 5 of 5 seeded bugs by rerunning pytest", tags: ["Code Agents", "AST"], metric: "5 of 5 seeded bugs fixed and verified", repo: GH + "repo-aware-codebase-agent" },
  { title: "Cross Session Agent Memory", track: "ai", desc: "Chatbots forget everything when the process exits, so implemented SQLite persisted episodic, semantic and procedural memory with fact extraction and exponential decay, recalling stored facts after a simulated process restart", tags: ["Memory", "CoALA"], metric: "42 tests, restart recall proven from disk", featured: true, repo: GH + "cross-session-agent-memory" },
  { title: "Agent Trajectory Eval Harness", track: "ai", desc: "Final answer scoring hides bad agent behavior, so built a harness scoring whole trajectories with an LLM as judge, whose CI gate passed 1 good agent and failed all 4 broken ones", tags: ["Evaluation", "LLM as Judge"], metric: "CI gate failed 4 of 4 broken agents", repo: GH + "agent-trajectory-eval-harness" },

  // ---- Data Engineer -----------------------------------------------------
  { title: "CSV to Database ETL", track: "data", desc: "Messy sales exports with mixed dates, missing prices and duplicates blocked reporting, so built an idempotent pandas and SQLAlchemy ETL turning 1,030 rows into 961 clean rows, dropping 39 unpriced and 30 duplicate orders", tags: ["ETL", "SQL"], metric: "1,030 raw rows to 961 clean rows", repo: GH + "csv_to_db_etl" },
  { title: "API to Data Lake: Weather", track: "data", desc: "Hourly weather for ten cities came from a flaky API, so engineered retrying ingestion into raw JSON and partitioned Parquet where one failed city never stops the run and reruns never duplicate rows", tags: ["API", "Parquet"], repo: GH + "api_to_datalake_weather" },
  { title: "Dockerized Pipeline", track: "data", desc: "Works on my laptop failures blocked sharing an ETL, so containerized it with Docker Compose and PostgreSQL, gated startup on a health check and ran as non root, so one command reproduces it", tags: ["Docker"], repo: GH + "dockerize_pipeline" },
  { title: "dbt Analytics Engineering", track: "data", desc: "Raw ecommerce exports with duplicate customers and orders needed trusted reporting tables, so built dbt staging and mart layers on DuckDB, deduplicating with window functions until 9 models build and 31 tests pass", tags: ["dbt", "Data Modeling"], metric: "9 models build, 31 tests pass", repo: GH + "dbt_analytics_engineering" },
  { title: "Airflow Orchestrated Pipeline", track: "data", desc: "A weather ETL script needed scheduling, retries and backfills, so rebuilt it as an Apache Airflow DAG with 3 retries and backoff, keeping logic testable so reruns overwrite by date without duplicates", tags: ["Airflow"], metric: "3 retries with backoff, idempotent by run date", repo: GH + "airflow_orchestrated_pipeline" },
  { title: "End to End ELT", track: "data", desc: "Crypto market data needed a traceable path to a dashboard, so built an ELT chain landing raw data in DuckDB, transforming with dbt staging and marts, serving Streamlit and scheduling daily on GitHub Actions", tags: ["ELT", "dbt", "Streamlit"], repo: GH + "end_to_end_elt" },
  { title: "PySpark at Scale", track: "data", desc: "Ten million taxi trips outgrow pandas, so built a PySpark pipeline ranking top fares with window functions, broadcasting an 18 row zone lookup to skip a shuffle and writing idempotent Parquet by pickup date", tags: ["PySpark", "Big Data"], repo: GH + "pyspark_big_data" },
  { title: "Data Quality Framework", track: "data", desc: "Bad data flows downstream unnoticed, so built a Pandera quality gate covering freshness, volume and schema drift that quarantines failing rows, exits non zero for CI and catches all 20 planted problems", tags: ["Pandera", "Data Quality"], metric: "20 of 20 planted problems caught", repo: GH + "data_quality_framework" },
  { title: "CI/CD for Data Pipelines", track: "data", desc: "Pipeline changes needed a safety net before merge, so wired GitHub Actions to lint SQL with sqlfluff, run pytest and dbt build on every pull request with SHA pinned actions and read only permissions", tags: ["CI/CD", "dbt"], repo: GH + "cicd_data_pipelines" },
  { title: "Kafka Streaming", track: "data", desc: "Nightly batches leave aggregates stale, so built an Apache Kafka pipeline keyed by symbol across 3 partitions, computing one minute event time windows with a watermark and idempotent upserts safe on replay", tags: ["Kafka", "Streaming"], metric: "1 minute windows, 3 partitions, idempotent upserts", repo: GH + "realtime_streaming_kafka" },
  { title: "AWS Data Lake", track: "data", desc: "Retail orders needed SQL access without servers, so built a medallion data lake on Amazon S3, AWS Glue and Amazon Athena with partitioned Parquet and idempotent CTAS transforms, tested offline with moto and DuckDB", tags: ["AWS", "S3", "Glue", "Athena"], repo: GH + "aws_data_lake" },
  { title: "Infrastructure as Code: Terraform", track: "data", desc: "Console clicking made cloud setups unrepeatable, so defined an AWS S3, Glue Catalog and IAM data lake in Terraform with encrypted versioned buckets and public access blocks, so one command creates or destroys it", tags: ["Terraform", "IaC"], repo: GH + "infrastructure_as_code_terraform" },
  { title: "Snowflake and dbt Warehouse", track: "data", desc: "Snowflake trial credits are limited, so built a dbt star schema that runs on DuckDB for free practice and targets Snowflake by config change, covering COPY INTO staging, time travel and zero copy cloning", tags: ["Snowflake", "dbt"], repo: GH + "14_snowflake_dbt_warehouse" },
  { title: "CDC Pipeline", track: "data", desc: "Nightly full reloads strain production databases, so built change data capture with a watermark poller and a Debezium track sharing one idempotent SCD2 apply core handling upserts, deletes and out of order changes", tags: ["CDC", "Debezium", "Kafka"], repo: GH + "cdc_pipeline" },
  { title: "Web Scraping Pipeline", track: "data", desc: "Useful data sat on pages without an API, so built a polite scraper with a robots.txt check, 1 second delay and 3 retries, tested on a frozen HTML fixture and scheduled through GitHub Actions", tags: ["Scraping", "Scheduling"], repo: GH + "web_scraping_pipeline" },
  { title: "Kafka and Spark Streaming", track: "data", desc: "Late events distort windowed counts, so built Apache Kafka feeding Spark Structured Streaming with event time windows and a 2 minute watermark, absorbing a producer that delays 10% of events", tags: ["Kafka", "Spark"], metric: "2 minute watermark against 10% late events", repo: GH + "kafka_spark_streaming" },
  { title: "Lakehouse: Delta and Iceberg", track: "data", desc: "Plain Parquet cannot update, delete or undo, so built a Delta Lake weather lakehouse with delta-rs adding ACID MERGE, time travel and schema evolution, plus a PySpark version and Iceberg comparison notes", tags: ["Delta Lake", "Iceberg"], repo: GH + "lakehouse_delta_iceberg" },
  { title: "GCP Serverless Pipeline", track: "data", desc: "Cloud pipelines rarely run without paid accounts, so built a Google Cloud Function and BigQuery pipeline with a Cloud Scheduler rollup where one RUN_MODE switch runs identical Python locally on DuckDB or serverless", tags: ["GCP", "BigQuery"], repo: GH + "gcp_serverless_pipeline" },
  { title: "Data Observability", track: "data", desc: "Silent pipeline failures go unnoticed, so instrumented a daily ETL with stored run metrics and five checks for failed runs, volume drops, duration spikes, freshness and schema drift, alerting a webhook on warnings", tags: ["Observability"], metric: "5 anomaly checks, severity gated alerts", repo: GH + "data_observability" },
  { title: "Kubernetes Data Service", track: "data", desc: "A data API needed to absorb traffic spikes, so containerized a FastAPI service and wrote Kubernetes manifests with health probes and an autoscaler scaling 2 to 6 replicas at 50% CPU", tags: ["Kubernetes", "FastAPI"], metric: "2 to 6 replicas at 50% CPU", repo: GH + "kubernetes_data_service" },
  { title: "CDC to Vector Freshness Pipeline", track: "data", desc: "RAG chatbots keep citing edited documents because vector search cannot flag stale results, so built change data capture into Qdrant with deterministic chunk ids and a staleness dashboard, backed by 57 passing tests", tags: ["CDC", "Qdrant", "RAG"], metric: "57 passing tests", repo: GH + "cdc_vector_freshness_pipeline" },
  { title: "Data Contract Enforcement Gateway", track: "data", desc: "Upstream schema changes silently break consumers, so built a gate that proves Avro compatibility by deserializing old bytes with new schemas, blocking breaking changes before Apache Kafka, backed by 29 offline tests", tags: ["Kafka", "Schema Registry"], metric: "29 offline tests, real broker validated", featured: true, repo: GH + "data_contract_enforcement_gateway" },
  { title: "Semantic Layer and Reverse ETL", track: "data", desc: "Monthly recurring revenue had three conflicting definitions, so defined one dbt MetricFlow metric cross checked against Cube, exposing a fan out bug that reported $145,222 against a true $6,140 before syncing to a CRM", tags: ["dbt MetricFlow", "Reverse ETL"], metric: "Reported $145,222 against true $6,140, a 23.6x error", repo: GH + "semantic_layer_reverse_etl" },
  { title: "Warehouse FinOps Dashboard", track: "data", desc: "Materialization choices hid warehouse cost, so priced dbt models from lineage and measured Parquet bytes at BigQuery rates, flagging a view costing 94x an incremental model, with a CI gate that fails on waste", tags: ["FinOps", "dbt"], metric: "View costs 94x incremental, 81% of spend", repo: GH + "warehouse_finops_dashboard" },
  { title: "Real Time Feature Store", track: "data", desc: "A naive join scored 0.859 offline but 0.263 live from train and serve skew, so built a Feast feature store with shared transforms and point in time correct joins holding 0.842 live", tags: ["Feast", "MLOps"], metric: "Live accuracy 0.263 to 0.842", repo: GH + "realtime_feature_store_ml" },
  { title: "Pipeline Lineage Graph", track: "data", desc: "Schema changes could not be traced to downstream columns, so instrumented a three step ELT with OpenLineage and built a column level graph showing the source amount column breaks 2 columns across 2 jobs", tags: ["OpenLineage", "Marquez"], metric: "Impact analysis: 2 columns, 2 jobs", repo: GH + "pipeline_lineage_graph" },
  { title: "LLM Assisted dbt Generator", track: "data", desc: "Manual dbt tests miss business rule bugs, so built a generator drafting models and tests from a business glossary behind a human review gate, lifting recall on 8 planted bugs from 50% to 100%", tags: ["LLM", "dbt"], metric: "Bug catch recall 50% to 100%", repo: GH + "llm_dbt_generator" },

  // ---- Quant ---------------------------------------------------------
  { title: "Pairs Trading Stat Arb Engine", track: "quant", desc: "Structural breaks end mean reversion and blow up pairs trades: built a Kalman filter hedge ratio with a news regime gate that vetoes entries, cutting max drawdown 22.6% to 7.2% on a synthetic pair", tags: ["Cointegration", "Kalman Filter"], metric: "Max drawdown cut 68%", featured: true, repo: GH + "pairs-trading-statarb" },
  { title: "Options Greeks and Vol Surface Cockpit", track: "quant", desc: "Per contract implied vol inversion is too slow to reprice an option chain: trained a neural net surrogate on an SVI calibrated surface, repricing 90 contracts over 300x faster at 1.93 vol points RMSE", tags: ["Options", "Vol Surface"], metric: "334x to 447x faster over 90 contracts", repo: GH + "options-greeks-vol-surface" },
  { title: "Low Latency Market Data Engine", track: "quant", desc: "Trading engines need market data decisions in microseconds: engineered a C++20 UDP ingest into an in memory limit order book with Redis state, sustaining 100k+ updates per second at about 250 ns P50 latency", tags: ["C++20", "Order Book"], metric: "100k+ updates/sec, ~250ns P50, ~1200ns P99", featured: true, repo: GH + "market-engine-deploy" },
  { title: "Market Making Engine", track: "quant", desc: "Market makers accumulate inventory risk with every fill: built an Avellaneda Stoikov quoting strategy on a C++20 price time priority order book, cutting inventory standard deviation from 14.99 to 5.92 against a naive baseline", tags: ["Market Making", "Inventory Risk"], metric: "Inventory risk down ~60%", repo: GH + "market-making-avellaneda-stoikov" },
  { title: "Optimal Execution: RL vs Almgren Chriss", track: "quant", desc: "Selling a large order fast costs market impact and selling slowly adds price risk: trained a PPO agent within 4% of the Almgren Chriss closed form optimum, objective 36.40 versus 35.00", tags: ["Reinforcement Learning", "Execution"], metric: "Within 4% of closed form optimum", repo: GH + "almgren-chriss-optimal-execution" },
  { title: "VaR and Expected Shortfall Engine", track: "quant", desc: "Uncalibrated VaR misleads risk decisions: built five VaR and Expected Shortfall methods plus an EVT tail and backtested them with Kupiec and Christoffersen tests, where Normal failed and four methods calibrated", tags: ["Risk", "Backtesting"], metric: "4 of 5 methods calibrated over 949 days", repo: GH + "var-es-risk-engine" },
  { title: "Deflated Sharpe Ratio Auditor", track: "quant", desc: "Selecting the best of many backtests inflates Sharpe by luck: implemented Probabilistic and Deflated Sharpe Ratio from scratch, which flagged a noise strategy at Sharpe 1.40 and passed only 1 of 100 strategies", tags: ["Sharpe Ratio", "Multiple Testing"], metric: "99 of 100 strategies flagged as overfit", repo: GH + "deflated-sharpe-ratio-auditor" },
  { title: "Brinson Fachler Attribution", track: "quant", desc: "Naive summing of period attribution drifts from true compounded active return: implemented Brinson Fachler allocation and selection with Carino linking, removing a 347 basis point drift over 24 periods and reconciling to machine precision", tags: ["Performance Attribution"], metric: "347 basis point drift removed over 24 periods", repo: GH + "brinson-fachler-attribution" },
  { title: "Algo Zoo Prediction Lab", track: "quant", desc: "Model comparisons without significance tests reward luck: benchmarked ARIMA, Ridge, Lasso, kNN, Random Forest and Gradient Boosting on identical walk forward folds with Diebold Mariano tests, and none beat the naive baseline", tags: ["Forecasting", "Statistical Testing"], metric: "No model beat the naive baseline", repo: GH + "algo-zoo-prediction-lab" },
  { title: "GARCH Volatility Forecasting", track: "quant", desc: "Variance forecasts are noisy and easy to overrate: benchmarked walk forward GARCH(1,1) against EWMA and rolling baselines on QLIKE, then applied volatility targeting to cut realized volatility from 14% to 10%", tags: ["GARCH", "Volatility"], metric: "Realized volatility 14% to 10%", repo: GH + "garch-vol-forecasting" },
  { title: "Cointegration Lead Lag Network", track: "quant", desc: "Testing every pair in a universe manufactures false discoveries: screened a synthetic universe for cointegration and Granger lead lag with Benjamini Hochberg FDR correction, pruning 15 raw edges to 3", tags: ["Cointegration", "Network Analysis"], metric: "15 raw edges pruned to 3, 60% of pairs held out of sample", repo: GH + "cointegration-leadlag-network" },
  { title: "Order Book ML Alpha", track: "quant", desc: "Accuracy is not a strategy until it pays the spread: built a limit order book pipeline with causal features, where a 53% accurate model turned gross 0.97 ticks per trade into a net loss", tags: ["Order Book", "Machine Learning"], metric: "Gross 0.97 ticks per trade, net below zero after spread", repo: GH + "orderbook-ml-alpha" },
  { title: "Alt Data Alpha", track: "quant", desc: "Apparent alt data edge is often leakage: scored one signal three ways with point in time lags and purged CV, cutting the Information Coefficient from 0.32 to 0.10 and exposing two thirds as leakage", tags: ["Alt Data", "Leakage"], metric: "IC 0.32 in sample, 0.10 leakage safe", repo: GH + "altdata-alpha" },
  { title: "Triple Barrier Signal Research", track: "quant", desc: "Fixed horizon labels overlap and shuffled cross validation leaks them across folds: built triple barrier labeling with a purged embargoed KFold splitter, exposing a 7.6 point accuracy overstatement from naive KFold on identical data", tags: ["Triple Barrier", "Purged CV"], metric: "Naive KFold overstated accuracy by 7.6 points", repo: GH + "triple-barrier-signal-research" },
  { title: "Kaggle Quant Competition", track: "quant", desc: "Shuffled CV leaks on time ordered data: built a synthetic Optiver style pipeline with purged date ordered CV, where LightGBM cut MAE from a 1.711 baseline to 1.595 and naive KFold falsely showed 1.583", tags: ["Kaggle", "Feature Engineering"], metric: "MAE 1.711 baseline to 1.595 LightGBM", repo: GH + "kaggle-quant-competition" },

  // ---- Hardware --------------------------------------------------------
  { title: "Embedded Systems Practice", track: "hardware", desc: "Built fundamentals across ESP32 sensing, actuation and networking: completed ten Wokwi simulated exercises from LED blink to debounced input, I2C OLED display, PIR alarm state, servo control and WiFi with MQTT telemetry", tags: ["ESP32", "Wokwi"], metric: "10 exercises in Wokwi simulation", repo: GH + "hardware-embedded-practice" },
  { title: "Keypad Door Lock v2", track: "hardware", desc: "Door locks must resist brute force and intrusion: engineered a four state machine in ESP32 C++ firmware with a Python twin, passing 42 unit tests and a 12 of 12 red team suite", tags: ["ESP32", "State Machine", "MQTT"], metric: "42 tests, 12/12 red team", repo: GH + "keypad-door-lock-v2" },
  { title: "TinyML Gesture Classifier", track: "hardware", desc: "Inference on a microcontroller needs a tiny model: trained a Keras gesture classifier on synthetic MPU6050 data and applied int8 quantization for a 15832 byte TFLite Micro model at 85% accuracy versus 100% float32", tags: ["TinyML", "Quantization"], metric: "Float32 100% vs int8 85% accuracy", repo: GH + "tinyml-gesture-classifier" },
  { title: "FreeRTOS Climate Monitor", track: "hardware", desc: "Single loop firmware lets a network stall freeze sensing: architected three FreeRTOS tasks on an ESP32 sharing a queue and mutexes, with a 10 second sustained alert and MQTT reporting that never blocks sensing", tags: ["FreeRTOS", "I2C"], metric: "3 FreeRTOS tasks, 11 tests passing", repo: GH + "freertos-climate-monitor" },
  { title: "Battery Powered Datalogger", track: "hardware", desc: "Coin cells cannot sustain an awake ESP32: engineered deep sleep firmware logging BME280 readings to SPI flash, with a datasheet based power budget estimating 27.5 days on a CR2032 at 60 second intervals", tags: ["Deep Sleep", "Power Budgeting"], metric: "272 uA average draw, ~27.5 days on a CR2032", repo: GH + "battery-powered-datalogger" },
  { title: "Custom PCB Smart Plug", track: "hardware", desc: "Overcurrent faults need debounced trips that ignore inrush: engineered an ESP32 relay and INA219 sensing state machine passing 30 tests and a 12 of 12 red team suite, with a two layer PCB specification", tags: ["PCB Design", "KiCad", "INA219"], metric: "30 tests, 12/12 red team", featured: true, repo: GH + "custom-pcb-smart-plug" },
  { title: "RFID and BLE Lock v2", track: "hardware", desc: "Access control needs two credential channels under one rule: built ESP32 firmware that toggles a servo bolt on an allow listed MFRC522 RFID tap or BLE passcode write and relocks after 15 seconds", tags: ["RFID", "BLE"], metric: "13 tests passing, SPI RFID plus BLE GATT", repo: GH + "rfid-ble-lock-v2" },
  { title: "IMU Sensor Fusion Node", track: "hardware", desc: "UART streams have no message boundaries: designed a 36 byte CRC checked protocol at 200 Hz feeding a C++20 host with a Kalman filter whose RMSE ran about 3x below a complementary filter", tags: ["Kalman Filter", "C++"], metric: "Kalman RMSE ~3x below complementary filter", repo: GH + "imu-sensor-fusion-node" },

  // ---- Health Tech ------------------------------------------------------
  { title: "HIPAA Deidentification Pipeline", track: "health", desc: "Patient data needs identifiers removed before use: built a HIPAA Safe Harbor pipeline that drops, generalizes and redacts identifiers, with a leak scan clean across 200 synthetic records and 2172 free text redactions", tags: ["HIPAA", "Privacy"], metric: "2,172 redactions, zero leaks", featured: true, repo: GH + "hipaa_deidentification" },
  { title: "Synthetic Patient Generator", track: "health", desc: "Analytics practice needs realistic patient data without real PHI: built a Java free generator writing Synthea shaped EHR CSVs and FHIR bundles with real SNOMED, LOINC and RxNorm codes, plus a population explorer", tags: ["Synthea", "Synthetic Data"], metric: "12 tests passing", repo: GH + "synthetic_patients_synthea" },
  { title: "HL7 v2 Parser", track: "health", desc: "Hospital systems exchange pipe delimited HL7 v2 messages that integration engineers must decode: built a parser for ADT and ORU messages with malformed input handling and JSON conversion, verified by 23 tests", tags: ["HL7"], metric: "23 tests passing", repo: GH + "hl7_v2_parser" },
  { title: "FHIR API Client", track: "health", desc: "Health apps read clinical data through FHIR REST APIs: built a FHIR R4 client with search, pagination and FHIRPath extraction, running identically offline and against the live HAPI FHIR server, with 14 tests", tags: ["FHIR", "REST"], metric: "14 tests, offline and live HAPI server", repo: GH + "fhir_api_client" },
  { title: "Medical Code Translator", track: "health", desc: "Billing and clinical systems code the same disease differently: built a FastAPI service that looks up and crosswalks ICD-10-CM, SNOMED CT, LOINC and CPT and normalizes drug names through the live RxNorm API", tags: ["ICD-10", "SNOMED", "LOINC"], metric: "16 tests, 5 code systems", repo: GH + "medical_code_translator" },
  { title: "HL7 to FHIR Converter", track: "health", desc: "Legacy HL7 v2 systems must feed FHIR apps: built a FastAPI converter mapping ADT and ORU messages to FHIR R4 Bundles with LOINC coded values, validated against the FHIR spec and 28 tests", tags: ["HL7", "FHIR"], metric: "28 tests, spec validated Bundles", repo: GH + "hl7_to_fhir_converter" },

  // ---- Product Manager --------------------------------------------------
  { title: "Product Teardown", track: "product", desc: "Improvement ideas need defensible prioritization: completed a full Duolingo teardown covering user, JTBD, business model and core loop, then ranked six improvements with RICE, putting first lesson onboarding at 5,000,000", tags: ["JTBD", "RICE"], metric: "6 ideas ranked, onboarding first at RICE 5,000,000", repo: GH + "product_teardown" },
  { title: "Writing a PRD", track: "product", desc: "Engineers need a spec covering what and why: authored an end to end PRD for Friend Streaks with user stories, guardrail metrics and rollout plan, sizing the A/B test at 16,842 users per variant", tags: ["PRD"], metric: "16,842 users per variant, 14 day window binds", repo: GH + "write_a_prd" },
  { title: "Metrics and North Star", track: "product", desc: "Teams need one metric to steer by: defined a Daily Active Learners North Star with a KPI tree and AARRR funnel, computed on synthetic data at 64.5% activation, 41.1% D7 retention and 28.4% stickiness", tags: ["Metrics", "AARRR"], metric: "64.5% activation, 28.4% stickiness on synthetic data", repo: GH + "metrics_north_star" },
  { title: "Competitive Analysis", track: "product", desc: "Market entry needs defensible sizing: mapped the language learning market with a feature matrix and positioning map, sizing TAM SAM SOM at $24.4B, $8.5B and $170.7M and reconciling bottom up within 10%", tags: ["Market Sizing"], metric: "SOM $170.7M top down vs $153.6M bottom up", repo: GH + "competitive_analysis" },
  { title: "User Research", track: "product", desc: "Product bets need evidence from users, not opinion: built a research method covering screener, discussion guide, affinity mapping, personas and JTBD, then synthesized 37 coded quotes from 8 illustrative interviews into two personas", tags: ["User Research"], metric: "50 screened, 8 interviews, 37 quotes, 2 personas", repo: GH + "user_research" },
  { title: "Prioritization and Roadmapping", track: "product", desc: "A messy backlog needs a defensible order: scored 20 ideas with RICE, ICE and Weighted frameworks, exposed their disagreements, and sequenced a Now Next Later roadmap with a stakeholder memo", tags: ["Roadmapping"], metric: "20 ideas, onboarding tops RICE at 5,000,000", featured: true, repo: GH + "prioritization_roadmap" },
];

const TRACK_META = {
  all:     { label: "All" },
  ai:      { label: "AI Engineering" },
  data:    { label: "Data Engineering" },
  product: { label: "Product Management" },
  hardware:{ label: "Hardware" },
  quant:   { label: "Quant" },
  health:  { label: "Health Tech" },
};
